import json
import os
import requests
import time

# List of Video IDs and Titles (will be populated/expanded)
# Load videos from JSON file generated by fetch_youtube_channel.py
json_path = os.path.join(os.path.dirname(__file__), "channel_videos.json")

videos = []
if os.path.exists(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        for entry in data:
            if entry.get('id'):
                videos.append({
                    "id": entry['id'],
                    "title": entry.get('title', 'Unknown Title')
                })
else:
    print(f"Metadata file not found at {json_path}. Please run fetch_youtube_channel.py first.")
    exit(1)

DEST_DIR = r"c:\Users\Admin\OneDrive\Desktop\Client Websites\dj-werra-website\public\assets\thumbnails"
if not os.path.exists(DEST_DIR):
    os.makedirs(DEST_DIR)

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Referer": "https://www.youtube.com/"
}

def download_thumb(video_id):
    path = os.path.join(DEST_DIR, f"{video_id}.jpg")
    
    # Try maxres, then hq, then mq
    qualities = ["maxresdefault", "hqdefault", "mqdefault"]
    
    for q in qualities:
        url = f"https://img.youtube.com/vi/{video_id}/{q}.jpg"
        print(f"Trying {url}...")
        try:
            r = requests.get(url, headers=HEADERS, timeout=10)
            if r.status_code == 200:
                with open(path, "wb") as f:
                    f.write(r.content)
                print(f"SUCCESS: {video_id} using {q}")
                return True
            else:
                print(f"Failed {q}: {r.status_code}")
        except Exception as e:
            print(f"Error {q}: {e}")
            
    return False

# Download
for v in videos:
    print(f"Processing {v['title']} ({v['id']})...")
    if not download_thumb(v['id']):
        print(f"FAILED ALL for {v['id']}")
